name: Close PRs Automatically

on:
  pull_request:
    types: [opened, synchronize]  # Se activa cuando se abre o se sincroniza un PR

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Close pull request if pushed to test or demo
        if: |
          github.event.pull_request.head.ref == 'test' || github.event.pull_request.head.ref == 'demo'
        run: |
          echo "PR targeting test or demo branch. Closing PR automatically."
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
