name: Close Pull Request for Test to Demo

on:
  workflow_run:
    workflows: ["Sync Migrations from Test to Demo"]  # Depende del flujo anterior
    types:
      - completed

permissions:
  pull-requests: write  # Permiso para escribir en pull requests

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Close open pull request from test to demo
        run: |
          PR_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:test&base=demo" | \
            jq '.[0].id')
          if [ "$PR_ID" != "null" ]; then
            echo "Closing pull request with ID $PR_ID..."
            curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"state": "closed"}' \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID"
          else
            echo "No open pull request found for test to demo."
          fi
