name: Sync Migrations from Demo to Main

on:
  pull_request:
    branches:
      - main  # Se ejecuta automáticamente al crear o actualizar un PR hacia "main"
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write  # Permiso para escribir en el repo
  checks: write  # Permiso para bloquear el PR si falla el job

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtener todo el historial para comparación

      - name: Configure Git user
        run: |
          git config --global user.name "kravmaga95"
          git config --global user.email "edwardsalex8034@gmail.com"
      
      - name: Authenticate Git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Ensure demo branch is up-to-date
        run: |
          git checkout demo || { echo "Error: branch 'demo' not found"; exit 1; }
          git pull --ff-only origin demo || { echo "Error pulling demo branch"; exit 1; }
      
      - name: Copy migration files from demo to temporary folder
        run: |
          if [ -d "demo/migrations" ]; then
            echo "Copying migration files from demo/migrations to temporary folder..."
            mkdir -p /tmp/migrations
            cp demo/migrations/* /tmp/migrations/
          else
            echo "Error: No migrations folder in demo."
            exit 1
          fi
      
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main || git checkout -b main origin/main
          git pull --ff-only origin main || { echo "Error pulling main branch"; exit 1; }
      
      - name: Ensure prod/migrations folder exists in main
        run: |
          if [ ! -d "prod/migrations" ]; then
            mkdir -p prod/migrations
            echo "Created prod/migrations folder in main."
          fi
      
      - name: Copy migration files from temporary folder to prod/migrations
        run: |
          echo "Copying migration files from temporary folder to prod/migrations..."
          cp /tmp/migrations/* prod/migrations/
      
      - name: Commit and push changes to main
        run: |
          git add prod/migrations/*
          git commit -m "Sync migration files from demo to main" || echo "No changes to commit"
          git push origin main || { echo "Push failed"; exit 1; }

    # Bloquea el merge si el workflow falla
    required: true
