name: Sync Migrations from Test to Demo

on:
  push:
    branches:
      - test  # Se ejecuta cuando hay un push en la rama "test"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "kravmaga95"
          git config --global user.email "edwardsalex8034@gmail.com"

      - name: Authenticate Git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/DEVOPSPRUEBAS/demo.git

      - name: Switch to test branch
        run: |
          git checkout test
          git pull origin test

      - name: Copy migration files to temp folder
        run: |
          mkdir -p /tmp/migrations_backup
          cp -r migrations/* /tmp/migrations_backup/

      - name: Switch to demo branch
        run: |
          git checkout demo
          git pull origin demo

      - name: Sync migrations folder
        run: |
          cp -n /tmp/migrations_backup/* migrations/

      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync new migration files from test to demo"
            git push origin demo
          fi
