name: Sync Migrations from Test to Demo

on:
  push:
    branches:
      - test  # Este workflow se ejecuta cuando hay un push en la rama 'test'

permissions:
  contents: write  # Permiso para escribir en el repositorio

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtener todo el historial para comparación

      - name: Configure Git user
        run: |
          git config --global user.name "kravmaga95"
          git config --global user.email "edwardsalex8034@gmail.com"

      - name: Authenticate Git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Ensure test branch is up-to-date
        run: |
          git checkout test
          git pull --ff-only origin test || { echo "Error pulling test branch"; exit 1; }

      - name: Check for migration files in test
        run: |
          # Verifica que la carpeta test/migrations exista desde la raíz del repositorio
          if [ ! -d "test/migrations" ]; then
            echo "No migrations folder found in test, exiting."
            exit 1
          fi
          echo "Migrations folder found in test."

      - name: Switch to demo branch
        run: |
          git fetch origin demo
          git checkout demo || git checkout -b demo origin/demo
          git pull --ff-only origin demo || { echo "Error pulling demo branch"; exit 1; }

      - name: Ensure migrations folder exists in demo
        run: |
          # Asegura que la carpeta demo/migrations existe, si no, la crea
          if [ ! -d "demo/migrations" ]; then
            mkdir -p demo/migrations  # Crea la carpeta si no existe
            echo "Created migrations folder in demo."
          fi

      - name: Copy new migration files from test to demo
        run: |
          # Verifica que existen archivos en test/migrations
          echo "Copying migration files from test to demo..."
          for file in test/migrations/*; do
            if [ ! -e "demo/migrations/$(basename $file)" ]; then
              cp "$file" demo/migrations/
              echo "Copied: $file"
            else
              echo "File $(basename $file) already exists in demo/migrations, skipping."
            fi
          done

      - name: Verify files copied to demo/migrations
        run: |
          echo "Listing files in demo/migrations after copy:"
          ls -l demo/migrations/

      - name: Commit and push changes
        run: |
          git add demo/migrations/*  # Asegura que solo los archivos de migrations se agreguen
          git status  # Verifica qué archivos están siendo agregados
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Sync migration files from test to demo"
            git push origin demo || { echo "Push failed"; exit 1; }
          fi
