name: Sync Migrations from Test to Demo

on:
  push:
    branches:
      - test  # Se ejecuta cuando hay un push en la rama "test"

permissions:
  contents: write  # Permiso para escribir en el repo

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtener todo el historial para comparación

      - name: Configure Git user
        run: |
          git config --global user.name "kravmaga95"
          git config --global user.email "edwardsalex8034@gmail.com"

      - name: Authenticate Git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Ensure test branch is up-to-date
        run: |
          git checkout test
          git pull --ff-only origin test || { echo "Error pulling test branch"; exit 1; }

      - name: Ensure demo branch is up-to-date
        run: |
          git fetch origin demo
          git checkout demo || git checkout -b demo origin/demo
          git pull --ff-only origin demo || { echo "Error pulling demo branch"; exit 1; }

      - name: Ensure migrations folder exists in demo
        run: |
          # Verifica si demo/migrations existe, si no, la crea en la ruta correcta.
          if [ ! -d "demo/migrations" ]; then
            mkdir -p demo/migrations  # Crea la carpeta si no existe
            echo "Created migrations folder in demo."
          fi

      - name: Checkout migration files from test branch to demo branch
        run: |
          echo "Checking out migration files from test branch into demo/migrations..."
          # Extrae solo los archivos de test/migrations y los coloca directamente en demo/migrations
          git checkout test -- test/migrations/*  # Copiar archivos de test/migrations en demo/migrations

      - name: Check for new files in demo/migrations and add them
        run: |
          # Revisa las diferencias entre demo y test en migrations y agrega los archivos que no existen en demo
          git diff --quiet || git add demo/migrations/*  # Si hay diferencias, agrega los archivos

      - name: Commit and push changes
        run: |
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Sync migration files from test to demo"
            git push origin demo || { echo "Push failed"; exit 1; }
